In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df.head()

fever  body pain  age  runnyNose  diffBreath  infectionProb
0   99.499060          0   84          1           0              1
1  101.580497          0   95          1           1              1
2  100.687373          0   55          0           1              1
3  101.074724          0   12          0           1              0
4   98.950076          0   82          1           1              0

In [4]:
df.tail()

fever  body pain  age  runnyNose  diffBreath  infectionProb
3044   99.955577          1   85          0           0              1
3045  101.198697          1   70          0           0              0
3046   98.228239          0   47          1           1              0
3047  100.938321          0   13          0           1              1
3048   99.799872          1    9          1           0              1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3049 entries, 0 to 3048
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fever          3049 non-null   float64
 1   body pain      3049 non-null   int64  
 2   age            3049 non-null   int64  
 3   runnyNose      3049 non-null   int64  
 4   diffBreath     3049 non-null   int64  
 5   infectionProb  3049 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 143.0 KB


In [6]:
df["diffBreadth"].value_counts()

KeyError: 'diffBreadth'

In [7]:
df["diffBreath"].value_counts()

0    1525
1    1524
Name: diffBreath, dtype: int64

In [8]:
df.describe()

fever    body pain          age    runnyNose   diffBreath  \
count  3049.000000  3049.000000  3049.000000  3049.000000  3049.000000   
mean     99.978482     0.514923    49.833388     0.507707     0.499836   
std       1.158225     0.499859    28.410918     0.500023     0.500082   
min      98.000419     0.000000     1.000000     0.000000     0.000000   
25%      98.993747     0.000000    26.000000     0.000000     0.000000   
50%      99.971490     1.000000    48.000000     1.000000     0.000000   
75%     100.997209     1.000000    74.000000     1.000000     1.000000   
max     101.999182     1.000000   100.000000     1.000000     1.000000   

       infectionProb  
count    3049.000000  
mean        0.494260  
std         0.500049  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

In [9]:
import numpy as np

In [13]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]
    

In [14]:
np.random.permutation(7)

array([4, 0, 2, 1, 6, 5, 3])

In [15]:
train, test = data_split(df, 0.2)

In [16]:
train

fever  body pain  age  runnyNose  diffBreath  infectionProb
351   100.824009          1    9          0           1              1
2779   99.330771          0   85          0           0              0
1188   98.986107          1   95          0           0              0
887    98.262144          0   28          0           1              0
1925   99.230431          0    7          0           1              1
...          ...        ...  ...        ...         ...            ...
1638  101.055093          1    2          1           1              1
1095  100.249099          1   75          1           1              1
1130   98.355114          1   85          0           1              0
1294   98.487511          0   82          0           1              0
860    99.393291          1   27          1           0              0

[2440 rows x 6 columns]

In [17]:
test

fever  body pain  age  runnyNose  diffBreath  infectionProb
1517  101.264441          0   77          0           1              0
2369   99.500560          1   62          1           1              0
1961  101.668644          0   89          1           0              0
343   100.492221          1    4          1           0              0
2663  101.369588          1   67          1           1              0
...          ...        ...  ...        ...         ...            ...
367    99.200180          0   38          0           1              0
845    98.921125          0   13          1           0              1
2312   98.348904          1   41          1           1              0
1413   99.604681          0   36          1           0              0
1366   99.036052          0   28          0           1              0

[609 rows x 6 columns]

In [24]:
X_train = train[['fever', 'body pain', 'age', 'runnyNose', 'diffBreath']]
X_test = test[['fever', 'body pain', 'age', 'runnyNose', 'diffBreath']]

In [25]:
X_train.to_numpy()
X_test.to_numpy()

array([[101.2644408 ,   0.        ,  77.        ,   0.        ,
          1.        ],
       [ 99.50055976,   1.        ,  62.        ,   1.        ,
          1.        ],
       [101.6686443 ,   0.        ,  89.        ,   1.        ,
          0.        ],
       ...,
       [ 98.34890406,   1.        ,  41.        ,   1.        ,
          1.        ],
       [ 99.60468116,   0.        ,  36.        ,   1.        ,
          0.        ],
       [ 99.0360521 ,   0.        ,  28.        ,   0.        ,
          1.        ]])

In [30]:
Y_train = train[['infectionProb']].to_numpy().reshape(2440, )
Y_test = test[['infectionProb']].to_numpy().reshape(609, )

In [31]:
Y_train

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
clf = LogisticRegression()
clf.fit(X_train, Y_train)

LogisticRegression()

In [36]:
clf.predict([[102, 90, 1, 1, 1]])

array([1], dtype=int64)

In [38]:
infection = clf.predict_proba([[102, 90, 1, 1, 1]])[0][1]

In [39]:
infection

0.9913694872647021